config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show] # ユーザーマイページへのルーティング
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :ryuyas
  root 'ryuyas#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hobby.rb
class Hobby < ApplicationRecord
end

app/models/ryuya.rb
class Ryuya < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
         has_many :ryuyas, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
         validates :name, presence: true #追記
         validates :profile, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     # deviseコントローラーにストロングパラメータを追加する          
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end

end

app/controllers/hobbys_controller.rb
class HobbysController < ApplicationController
    def index
        @hobbys = Hobby.all
    end

    def new
        @hobby = Hobby.new
      end
    
      def create
        hobby = Hobby.new(hobby_params)
        if hobby.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
    
      private
      def hobby_params
        params.require(:hobby).permit(:hobby_name, :genre, :price, :about, :spot)
      end
end

app/controllers/ryuyas_controller.rb
class RyuyasController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def top
  end
  
    def index
        if params[:search] == nil
            @ryuyas= Ryuya.all
          elsif params[:search] == ''
            @ryuyas= Ryuya.all
          else
            #部分検索
            @ryuyas = Ryuya.where("hobby_name LIKE ? ",'%' + params[:search] + '%')
          end
    end

    def new
        @ryuya = Ryuya.new
      end
    
      def create
        ryuya = Ryuya.new(ryuya_params)
        if ryuya.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @ryuya = Ryuya.find(params[:id])
      end

      def edit
        @ryuya = Ryuya.find(params[:id])
      end

      def update
        ryuya = Ryuya.find(params[:id])
        if ryuya.update(ryuya_params)
          redirect_to :action => "show", :id => ryuya.id
        else
          redirect_to :action => "new"
        end
      end
    
      def destroy
        ryuya = Ryuya.find(params[:id])
        ryuya.destroy
        redirect_to action: :index
      end

      private
      def ryuya_params
        params.require(:ryuya).permit(:hobby_name, :genre, :price, :about, :spot, :image)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobbys_helper.rb
module HobbysHelper
end

app/helpers/ryuyas_helper.rb
module RyuyasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hilite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
 <header>
  <h1>HobbyWorld</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>
 <footer>
      <p>Copyright © GeekSalon All Rights Reserved.</p>
 </footer>
</body>

</html>

app/views/ryuyas/edit.html.erb
<%= form_for @ryuya do |f| %>
    <%= f.label :hobby_name %>
    <%= f.text_field :hobby_name, :size => 140 %>
    <%= f.label :genre %>
    <%= f.text_field :genre, :size => 140 %>
    <%= f.label :price %>
    <%= f.text_field :price, :size => 140 %>
    <%= f.label :spot %>
    <%= f.text_field :spot, :size => 140 %>
    <%= f.label :about %>
    <%= f.text_field :about, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/ryuyas/index.html.erb
<h1>HobbyWorld</h1>
<h3>一覧ページ</h3>

<h4>投稿を検索</h4>
 <%= form_tag({controller:"ryuyas",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>

<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>

<%= link_to "新規投稿へ", new_ryuya_path %>

<div class=ryuyas-container">
  <% @ryuyas.each do |t| %>
    <div class=ryuya">
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.hobby_name %>
      <%= t.genre %>
      <%= t.price %>
      <%= t.about %>
      <%= t.spot %>
      <div class="main-box">
        <div class="left-container">
      </div>
        <div class="right-container">
          <%= link_to "詳細", ryuya_path(t.id) %>
          <%= link_to "編集", edit_ryuya_path(t.id) %>
          <%= button_to "削除", ryuya_path(t.id), method: :delete %>
        </div>
      </div>
        <p class="time"><%= t.created_at %></p>
    </div>
  <% end %>
</div>

<%= stylesheet_link_tag 'index', :media => "all" %>

app/views/ryuyas/new.html.erb
<h1>(自分の題名)</h1>
<h3>新規投稿ページ</h3>
<%= form_for @ryuya do |f| %>

  <div class="field">
    <%= f.label :hobby_name %>
    <%= f.text_field :hobby_name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :genre %>
    <%= f.select :genre, 
    [["スポーツ", "スポーツ"], 
    ["インドア", "インドア"], 
    ["アウトドア", "アウトドア"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price, :size => 10 %>
  </div>

  <div class="field">
    <%= f.label :about %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

<div class="field">
<%= f.label :spot %>
<%= f.text_field :spot, :size => 30 %>
</div>

<div class="field">
<%= f.label :image %>
<%= f.file_field :image %>

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", ryuyas_path %>

<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="post-container">
    <p class="title">投稿フォーム</p>
    <%= form_for(@ryuya, :url => { controller:'ryuyas', action:'create'})do |f| %>
    <%= f.label :投稿内容 %>
    <%= f.submit "送信"%>
    <br>
    <% end %>
</div>

app/views/ryuyas/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="ryuya">
  <p><%= @ryuya.hobby_name %></p>
  <p><%= @ryuya.genre %></p>
  <p><%= @ryuya.price %></p>
  <p><%= @ryuya.spot %></p>
  <p><%= @ryuya.about %></p>
  <p><%= @ryuya.created_at %></p>
</div>

<%= link_to "Tweet一覧に戻る", ryuyas_path %>

app/views/ryuyas/top.html.erb
<div class="first-block">
<body style="background-color:#eeeeee; margin: auto; text-align: center;">
<!-- Start cssSlider.com -->
  <div class='csslider1 autoplay '>
    <input name="cs_anchor1" id='cs_slide1_0' type="radio" class='cs_anchor slide' >
    <input name="cs_anchor1" id='cs_slide1_1' type="radio" class='cs_anchor slide' >
    <input name="cs_anchor1" id='cs_slide1_2' type="radio" class='cs_anchor slide' >
    <input name="cs_anchor1" id='cs_play1' type="radio" class='cs_anchor' checked>
    <input name="cs_anchor1" id='cs_pause1' type="radio" class='cs_anchor' >
    <ul>
      <div style="width: 100%; visibility: hidden; font-size: 0px; line-height: 0;">
        <img src="http://cssslider.com/sliders/pen/images/buns.jpg" style="width: 100%;">
      </div>
      <li class='num0 img'>
         <a href="http://cssslider.com" target=""><img src='/assets/hobby_images1.jpg' alt='INDOOR' title='INDOOR' /> </a> 
      </li>
      <li class='num1 img'>
         <a href="http://cssslider.com" target=""><img src='/assets/hobby_images4.jpg' alt='OUTDOOR' title='OUTDOOR' /> </a> 
      </li>
      <li class='num2 img'>
         <a href="http://cssslider.com" target=""><img src='/assets/hobby_images3.jpg' alt='SPORTS' title='SPORTS' /> </a> 
      </li>
    
    </ul>
    <div class='cs_description'>
      <label class='num0'>
        <span class="cs_title"><span class="cs_wrapper">INDOOR</span></span>
      </label>
      <label class='num1'>
        <span class="cs_title"><span class="cs_wrapper">OUTDOOR</span></span>
      </label>
      <label class='num2'>
        <span class="cs_title"><span class="cs_wrapper">SPORTS</span></span>
      </label>
    </div>
    <div class='cs_arrowprev'>
      <label class='num0' for='cs_slide1_0'></label>
      <label class='num1' for='cs_slide1_1'></label>
      <label class='num2' for='cs_slide1_2'></label>
    </div>
    <div class='cs_arrownext'>
      <label class='num0' for='cs_slide1_0'></label>
      <label class='num1' for='cs_slide1_1'></label>
      <label class='num2' for='cs_slide1_2'></label>
    </div>
    
    <div class='cs_bullets'>
      <label class='num0' for='cs_slide1_0'>
        <span class='cs_point'></span>
        <span class='cs_thumb'><img src='http://cssslider.com/sliders/pen/tooltips/buns.jpg' alt='INDOOR' title='INDOOR' /></span>
      </label>
      <label class='num1' for='cs_slide1_1'>
        <span class='cs_point'></span>
        <span class='cs_thumb'><img src='http://cssslider.com/sliders/pen/tooltips/croissant.jpg' alt='OUTDOOR' title='OUTDOOR' /></span>
      </label>
      <label class='num2' for='cs_slide1_2'>
        <span class='cs_point'></span>
        <span class='cs_thumb'><img src='http://cssslider.com/sliders/pen/tooltips/SPORTSie.jpg' alt='SPORTS' title='SPORTS' /></span>
      </label>
    </div>
    </div>
    <!-- End cssSlider.com -->
  
  <br /><br />
  </body>
<%= link_to "商品一覧", ryuyas_path %>
</div>
<div class="second-block">
</div>
<div class="third-block">
<!--   Third block Start   -->
  <section id="third-block">
    <p class="events-title">
      Recent Events
    </p>
    <div class="event-container">
      <div class="event">
        <image src="assets/hobby_images1.jpg"" class="event-image">
        <p class="event-name">
          <span>INDOOR</span>
        </p>
      </div>
      <div class="event">
        <p class="event-name">
          <span>OUTDOOR</span> 
        </p>
        <image src="assets/hobby_images2.jpg" class="event-image">
      </div>
      <div class="event">
        <image src="assets/hobby_images3.jpg" class="event-image">
        <p class="event-name">
          <span>SPORTS</span> 
        </p>
       </div>
    </div>
  </section>
  <!--   Third block End   -->

</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.ryuyas.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>

<%= link_to "Tweet一覧に戻る", ryuyas_path %>